# Automatisierung: Leave home

alias: Leave home
description: Schaltet das Licht im Wohnzimmer aus, wenn ich die Wohnung verlasse
trigger:
  - platform: zone
    entity_id: person.stevie
    zone: zone.home
    event: leave
condition:
  - condition: state
    entity_id: light.wohnzimmer
    state: 'on'
action:
  - service: light.turn_off
    target:
      area_id: wohnzimmer
mode: single
